service: serverless-dynamodb-scanner

custom:
  dynamodbTableArn: ''
  kinesisStreamArn: ''
  lastEvaluatedParameter: '/ddb-scanner/last-evaluated-key'

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ddb:Scan"
      Resource: {self:custom.dynamodbTableArn}
    - Effect: "Allow"
      Action:
        - "kinesis:PutRecords"
      Resource: {self:custom.kinesisStreamArn}
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:PutParameter"
      Resource: 'arn:aws:ssm:*:*:parameter/{self:custom.lastEvaluatedParameter}'
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:*:*:function:ScannerLambdaFunction"
  environment:
    TABLE_ARN: ${self:custom.dynamodbTableArn}
    STREAM_ARN: ${self:custom.kinesisStreamArn}
    LAST_EVALUATED_PARAMETER: ${self:custom.lastEvaluatedParameter}

functions:
  scanner:
    handler: handler.scanner
    timeout: 900
